oscoin/oscoin

README.rst

* Command is simpler, i.e. no `--tests` or `--main-is`
* Library code is also reloaded when changes are made
* We tell users about the selecting tests with a pattern.

Improve test run instructions

---

exe/node/Main.hs
src/Oscoin/Node.hs

`Oscoin.Node.storage` now takes parameters from the `NodeT` environment instead of arguments. This ensures that configuration and evaluation are the same.

Oscoin.Node.storage takes params from Node

---

src/Oscoin/Crypto/Hash.hs
src/Oscoin/Crypto/Hash/Mock.hs
src/Oscoin/Crypto/Hash/RealWorld.hs
test/Oscoin/Test/Crypto.hs

We rename `fromByteArray` to `hashByteArray` and relax the constraint from `ByteArray` to `ByteArrayAccess`.

Relax crypto hashing constraints

---

src/Database/SQLite/Simple/Orphans.hs
src/Oscoin/Storage/Block/SQLite.hs
src/Oscoin/Storage/Block/SQLite/Internal.hs
src/Oscoin/Storage/Block/SQLite/Transaction.hs
test/Oscoin/Test/Consensus/Node.hs
test/Oscoin/Test/Storage/Block/Equivalence.hs
test/Test/Oscoin/DummyLedger.hs

We replace the use of `RadTx` with `DummyTx` in the block store tests. This is one step towards getting rid of Radicle. The change also improves the run time of the block store tests by roughly 40%.
To achieve the transition we start by extracting `DummyTx` into the `Test.Oscoin.DummyLedger` module.
The interface for the SQLite storage had a `SQLite.ToRow tx` constraint for all transactions that was implemeted for `Tx c Radicle.Value`. A naive implementation of `SQLite.ToRow DummyTx` would lead to incompatibilities with the database schema. For this reason I introduced the `StoreTransaction` class. This constraint needs to be satisfied in order to store transactions in the database.

Replace RadTx with DummyTx in BlockStore tests

---

src/Oscoin/Storage/Block/Abstract.hs
test/Oscoin/Test/Storage/Block/Equivalence.hs

We do not run the protocol for the `getTip . insertBlock equivalance` test. The property under test is independent of running the protocol. This also reduces the time to run the test by a whopping 65%.

Do not run protocol for simple block storage tests

---

src/Oscoin/Storage/Block/Pure.hs
test/Oscoin/Test/Consensus.hs
test/Oscoin/Tests.hs

Since the block store is not responsible for chain selection and linking orphans anymore we remove some code and tests related to that.

Delete obsolete pure blockstore code

---

README.rst
test/Control/Concurrent/Tests.hs
test/Data/Conduit/Tests.hs
test/Main.hs
test/Test/Control/Concurrent/RateLimit.hs
test/Test/Data/Conduit/Serialise.hs
test/Test/Data/Sequence/Circular.hs

We move to a unified test organization by renaming the following modules
Control.Concurrent.Test.RateLimit -> Test.Control.Concurrent.RateLimit
Data.Conduit.Test.Serialise -> Test.Data.Conduit.Serialise
Data.Sequence.Circular.Tests -> Test.Data.Sequence.Circular
We also update the exports so that the exported group contains the fully
qualified module name.
Finally, we document this approach.

Reorganize non-oscoin tests

---

test/Main.hs
test/Oscoin/Tests.hs
test/Test/Oscoin/Crypto/Hash.hs
test/Test/Oscoin/Crypto/PubKey.hs

Move crypto tests from `Oscoin.Tests` to new `Test.Oscoin.Crypto.Hash` and `Test.Oscoin.Crypto.PubKey`.

Extract crypto tests from 'Oscoin.Tests'

---

src/Oscoin/P2P/Handshake.hs
src/Oscoin/P2P/Handshake/Simple.hs
test/Oscoin/Test/Crypto/PubKey/Arbitrary.hs
test/Oscoin/Test/P2P/Handshake.hs

Note that this doesn't prevent duplicate keys in the network.

Reject a peer presenting one's own public key in the handshake.

---

src/Oscoin/Node.hs
src/Oscoin/Node/Trans.hs

We replace `Oscoin.Node.Trans.withBlockStore` with `Oscoin.Node.Trans.getBlockStoreReader`. The new function can be used in more places and we do not need to get the BlockStore from the handle anymore.

Introduce getBlockStoreReader

---

README.rst
test/Main.hs
test/Oscoin/Tests.hs
test/Test/Oscoin/API.hs
test/Test/Oscoin/Node/Mempool.hs
test/Test/Oscoin/Storage/Block/Orphanage.hs

In three separate commits we
* move `Oscoin.Test.API` to `Test.Oscoin.API`
* move `Oscoin.Test.Storage.Block.Orphanage` to `Test.Oscoin.Storage.Block.Orphanage`
* extract `Test.Oscoin.Node.Mempool` from `Oscoin.Tests`

Move mempool, orphanage, API tests to new structure

---

test/Oscoin/Test/Storage/Block/SQLite.hs
test/Oscoin/Test/Util.hs
test/Test/Oscoin/Storage/Block/Orphanage.hs

* We eliminate the use of monadic properties
* We simplify `propInsertOrphans` replacing `genOrphanChainsFrom` with `arbitraryBlockChain`.

Simplify orphanage tests

---

src/Oscoin/Prelude.hs

We update `Oscoin.Prelude` to allow for a better development experience when using `notImplemented` and `undefined`.
During development `notImplemented` and `undefined` are often used to leave holes in the code. When running tests against code that contains multiple `notImplemented` statements we want to know which of these threw an error. For this we add the `HasCallstack` constraint to `notImplemented` and `undefined`.
We also start exporting `Protolude.error` from `Oscoin.Prelude` so that we can put some more information into errors during development.

Callstacks for debug and development prelude functions

---

src/Oscoin/Crypto/Blockchain/Block.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Oscoin/Test/Storage/Block/Cache.hs
test/Oscoin/Test/Storage/Block/SQLite.hs
test/Oscoin/Test/Storage/Block/SQLite/Blackbox.hs
test/Oscoin/Test/Storage/Block/SQLite/Whitebox.hs

This commit includes changes that improve the code in the `Oscoin.Crypto.Blockchain.Block` module.
We eliminate `genesisBlock`. This function was only used in one place where it was easily replaced by `emptyGenesisFromState`.
We eliminate the unused `withHeader` function.
We rewrite `linkParent` and `sealBlock` using lenses. This simplifies the code an reduces duplication. But more importantly we now guarantee the correctness of the `blockHash` field by using `blockHeaderL` instead of relying on us setting the field manually.

Cleanup 'Oscoin.Crypto.Blockchain.Block'

---

package.yaml
src/Oscoin/API/HTTP.hs
src/Oscoin/API/HTTP/Handlers.hs
src/Oscoin/API/HTTP/Internal.hs
test/Oscoin/Test/API/HTTP.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Oscoin/Test/Telemetry.hs

This removes all support for content type negotiation and JSON encoding from the HTTP API. The HTTP API only supports the CBOR content type now
We stop maintaining the JSON because of the following reasons:
* There is no strong use case to provide multiple encodings.
* Support for the JSON encoding was incomplete. Some endpoints were only available as CBOR.
* The JSON encoding requires us to write `ToJSON`/`FromJSON` instances in addition to `Serialise` instances.
As a consequence of removing content type negotiation support we get rid of 200 lines of code and cut the test time in half.
Supersedes #433

Remove JSON support for HTTP API

---

test/Oscoin/Test/Crypto/Blockchain.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Arbitrary.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Generators.hs
test/Oscoin/Test/Crypto/Blockchain/Generators.hs
test/Oscoin/Test/Storage/Block/SQLite/Blackbox.hs
test/Oscoin/Test/Storage/Block/SQLite/Whitebox.hs
test/Test/Oscoin/P2P/Gen.hs

We move all block generators from `Oscoin.Test.Crypto.Blockchain.Block.Arbitrary` to the `Oscoin.Test.Crypto.Blockchain.Block.Generators` module that already contained the majority of block generators. The `Arbitrary` modules only provides the necessary orphan `Arbitrary` instances.

Consolidate and document block generators

---

src/Oscoin/API/Types.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
src/Oscoin/Node/Mempool/Internal.hs
src/Oscoin/P2P/Types.hs
test/Oscoin/Test/API/HTTP.hs
test/Oscoin/Test/Crypto/Blockchain.hs

Remove a bunch of 'ToJSON' and 'FromJSON' that are not needed anymore due to #481. This does not remove all the instances quite yet.

Remove a bunch of 'ToJSON' and 'FromJSON' instances

---

exe/node/Main.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
test/Main.hs
test/Oscoin/Test/Crypto/Blockchain.hs
test/Test/Oscoin/Crypto/Blockchain/Eval.hs

`evalBlock` is updated to produce the new state and the receipts from block transactions. This functionality will be used by the Ledger abstraction in the future.
We also add tests for `evalBlock` and move the tests for `buildBlock` into the same module.
Finally, we eliminate the unused `evalBlockchain` functions.

Update 'evalBlock' to make it more powerful

---

test/Oscoin/Test/Crypto/Blockchain/Generators.hs
test/Oscoin/Test/Storage/Block/Equivalence.hs
test/Test/Oscoin/Storage/Block/Orphanage.hs

We change the blockchain generator so that
* the length of the blockchain is arbitrary instead of fixed by the size
* the length of the generated blockchain is limited to 15.
Since generating blockchains is expensive limiting the size speeds up the tests by about 15%.

Sized blockchain generators with reduced length

---

test/Main.hs
test/Oscoin/Test/Storage/Block/Equivalence.hs
test/Test/Oscoin/Protocol.hs

We extract the tests that test the protocol against the `STM` blockstore into a separate module. We also change the test implementation so that there is no need to monkey patch `insertBlock`.

Extract protocol equivalence tests

---

src/Oscoin/Prelude.hs

This prevents the `Oscoin.Prelude` being included in the call stacks created by `undefined` and `notImplemented`.

Freeze callstack for 'Oscoin.Prelude.undefined'

---

exe/node/Main.hs
src/Oscoin/API/HTTP/Handlers.hs
src/Oscoin/Consensus/Mining.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
src/Oscoin/Node.hs
src/Oscoin/Node/Trans.hs
src/Oscoin/Storage/Block/Memory.hs
src/Oscoin/Storage/Ledger.hs
src/Oscoin/Storage/Receipt.hs
test/Main.hs
test/Oscoin/Test/Consensus/Nakamoto.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/API.hs
test/Test/Oscoin/DummyLedger.hs
test/Test/Oscoin/Storage/Ledger.hs

We introduce the `Ledger` abstraction which wraps the block store, state store, and receipt store. The purpose of the `Ledger` is to provide consistent access to block artifacts (states and receipts). This commit only integrates the ledger with `Oscoin.Node`, `Oscoin.Consensus.Mining`, and the `Oscoin.Test.Consensus.Nakamoto`. It remains to integrate the ledger with `Protocol` where it will replace the `BlockStore`.
Todo

Introduce 'Ledger' for Node, Miner, and tests

---

data/blockstore.sql
data/genesis.yaml
src/Database/SQLite/Simple/Orphans.hs
src/Oscoin/Crypto/Blockchain/Block.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
src/Oscoin/Storage/Block/SQLite.hs
src/Oscoin/Storage/Block/SQLite/Internal.hs
src/Oscoin/Storage/Ledger.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Generators.hs
test/Test/Oscoin/Crypto/Blockchain/Eval.hs

This is a stepping stone in fixing #497.
This has to be considered "Part I" as it adds the height to the `BlockHeader` but it doesn't reap the benefits out of it (i.e. we can simplify and speed some of our SQLite queries as we now have an index on the `height` field).
I have decided, for review purposes, to include that in a subsequent PR (branching off either from this or from `master` if this PR ends up being merged quickly).

Add the height to the block header (Part I)

---

src/Oscoin/Storage/Block/SQLite/Internal.hs
test/Oscoin/Test/Storage/Block/SQLite/Whitebox.hs

This PR builds on top of #514 . It replaces most if not all the usages of `timestamp` in our SQLite queries with `height`. When not strictly necessary, I suspect it might help making things consistent on the long run (plus, there is an index on the `height`, which might speed up some queries in some circumstances).

Modify SQLite.Internal queries to use the height

---

exe/node/Main.hs
package.yaml
src/Oscoin/CLI/Command.hs
src/Oscoin/Consensus/Nakamoto.hs
src/Oscoin/Consensus/Nakamoto/Lenient.hs
src/Oscoin/Telemetry.hs
src/Oscoin/Telemetry/Events.hs
src/Oscoin/Telemetry/Trace.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Generators.hs

This PR delivers a simple instrumentation mechanism for pure code by introducing three types:
- A `Traced` (co)monad, suitable to annotate pure values with "tracing" (i.e. events);
- A `Probe`, which can be used to actually _emit_ the traced events;
- A `Traced` type alias which removes the need for the user to remember to pass `HasCallStack` everywhere.
While working on #432, we had this `chainDifficulty` function:
```haskell
-- | Calculate the difficulty of a blockchain.
chainDifficulty :: [Block c tx s] -> Difficulty
chainDifficulty [] =
minDifficulty
chainDifficulty (NonEmpty.fromList -> blks)
| NonEmpty.length blks `mod` fromIntegral difficultyBlocks == 0 =
encodeDifficulty $ fst (decodeDifficulty currentDifficulty)
* fromIntegral targetElapsed
`div` toInteger actualElapsed
| …
```

Allow instrumentation of pure code (Trace & Probes)

---

exe/node/Main.hs
package.yaml
snapshot.yaml
src/Oscoin/P2P/Disco.hs
src/Oscoin/P2P/Disco/GCE.hs
src/Oscoin/P2P/Disco/Options.hs
test/Test/Oscoin/P2P/Disco.hs

Discovery of peers when running on GCE, using `compute.instances.aggregatedList`.
This is part of the grander plan to go with plain (container) instances vs. some ~~security and configuration management nightmare~~ scheduling system. Note that the utility (and necessity) is limited to the "devnet" environment, which will feature a relatively small number of instances, and high churn (continuous deployment, developer ad-hoc deployments). "Testnet" and beyond is expected to have a (mostly) stable set of seed nodes deployed as a separate instance group, so DNS discovery is less of a configuration management concern.
Pro tip: if you install the `btc` GHC plugin, you may be able to earn a block reward for compiling `gogol-compute`.
**Alternatives considered**
* Make instances "register" …

GCE discovery

---

exe/node/Main.hs
src/Oscoin/CLI/KeyStore.hs
src/Oscoin/Node/Options.hs

This is useful for "ephemeral" deployments (i.e. locally or on the "devnet"). Otherwise, a proper KMS has to be set up, managed, and the application needs to know how to retrieve key material from there.
It _might_ be sufficient to not write these keys to disk, which would mean that if an instance gets rescheduled or rebooted, it appears as new.

Add option to create keypair if missing

---

.hlint.yaml
exe/node/Main.hs
src/Oscoin/Configuration.hs
src/Oscoin/Node/Options.hs
src/Oscoin/P2P/Disco.hs
src/Oscoin/P2P/Disco/Options.hs
src/Oscoin/P2P/Types.hs
src/System/Console/Option.hs
test/Main.hs
test/Test/Oscoin/Configuration.hs
test/Test/Oscoin/Configuration/Gen.hs
test/Test/Oscoin/Node/Options.hs
test/Test/Oscoin/Node/Options/Gen.hs
test/Test/Oscoin/P2P.hs
test/Test/Oscoin/P2P/Disco.hs
test/Test/Oscoin/P2P/Disco/Options.hs
test/Test/Oscoin/P2P/Disco/Options/Gen.hs
test/Test/Oscoin/P2P/Gen.hs
test/Test/Oscoin/P2P/Types.hs

i.e. render CLI options from a Options value
It is desirable for certain deployment configurations to be able to safely override the configuration of the deployed executable. For this, we need to be able to render the set of CLI options which fully constitute the configuration from the configuration value itself.
Ideally, the (partial) isomorphisms would be built up field-wise  à la [invertible syntax](http://www.informatik.uni-marburg.de/~rendel/unparse/). I have, however, not yet found a satisfying formulation. Of course, we could just define suitable functions `a -> [Opt Text]`, yet this is quite error prone. Reading the latest in [~~hipster~~higher kinded data](https://chrispenner.ca/posts/hkd-options) experiments, it occured to me that would be quite nice syntactically and …

Make (node) options invertible

---

cloudbuild.yaml
scripts/ci-cache.sh
src/Oscoin/Data/Ledger.hs

The same SHA1 doesn't get rebuilt, so fast-forward merges to master won't actually publish any artifacts. Our latest Doge image is from Apr 11.
It is anyways generally useful to be able to spin up a non-master container image, and _potentially_ to look at API docs (because Haddock markup is hard). I would, however, also be fine to not generate/publish Haddocks at all, as nobody is looking at them.

Always publish artifacts

---

cloudbuild.yaml
scripts/docker/build-image.sh
scripts/docker/haskell-scratch/Makefile

We've been happily using [fpco/haskell-scratch](https://github.com/fpco/haskell-scratch) as the base image for our docker images, not realising that it was last updated about 4 years ago, and inevitably our containers stopped working due to an outdated `libc`.
Since we are linking statically, the only "safe" thing to do is to use the exact same system libraries that are used for building the executables. Hence, we assemble the base image as part of the main build, based on the image we use for building. 
This is rather cheap and prevents any footgunning as we have switched the base image frequently in the past.

Build haskell-scratch base image to match build base

---

scripts/docker/haskell-scratch/Makefile

a) It does not actually work due to missing libreadline
b) The 1st commandmend of dogesec: "Thou shalt not have any executables besides
the entrypoint"

Base image: Remove /bin/sh

---

src/Oscoin/API/Client.hs
src/Oscoin/API/HTTP.hs
src/Oscoin/API/HTTP/Handlers.hs
src/Oscoin/API/HTTP/Internal.hs
src/Oscoin/API/Types.hs
src/Oscoin/Crypto/Blockchain/Block.hs
src/Oscoin/Node/Mempool/Internal.hs
test/Main.hs
test/Oscoin/Tests.hs
test/Test/Oscoin/API/HTTP.hs

The code in `Oscoin.API.HTTP.Handlers` and related modules is now 
polymorphic in the transaction type. See #552.
As part of this change we also eliminate the `getAllTransactions` endpoint.
It’s implementation did not use a serialisation of a transaction list but
rather a serialisation of the Mempool instance. This coupled the API to the
concrete mempool instance used by the node.

Make API polymorphic in 'tx'

---

test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/API.hs
test/Test/Oscoin/API/HTTP.hs

We add a test for invalid transactions with `Oscoin.API.Client.submitTransaction` in `Test.Oscoin.API`. This allows us to remove the low-level test from `Test.Oscoin.API.HTTP`.
We also remove the so called “smoke tests” from the API. This behavior is also covered by the tests for `Oscoin.API.Client.submitTransaction`.

Extend API.Client test, remove redundant tests

---

test/Oscoin/Test/API/HTTP/TestClient.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/API.hs
test/Test/Oscoin/API/HTTP.hs

This PR makes some of the functions inside `Test.API.HTTP.Helpers` a bit more polymorphic (in the seal) so that `nodeState` and `withNode` can be used also elsewhere (namely, in the tests for node syncing, to name one) skipping the tedious step of crafting a full-fledged `Node.Handle`.

Make withNode and nodeState polymorphic in the seal

---

cloudbuild.yaml
exe/deploy/Main.hs
exe/git-remote-helper/Main.hs
package.yaml
scripts/deploy/gce/bootstrap
scripts/deploy/gce/node
scripts/docker/publish-image.sh
src/Oscoin/Consensus/Nakamoto/Lenient.hs
src/Oscoin/Deployment.hs
src/Oscoin/Deployment/Internal/CloudInit.hs
src/Oscoin/Deployment/Internal/Docker.hs
src/Oscoin/Deployment/Internal/GCE.hs
src/Oscoin/Deployment/Internal/Systemd.hs
src/Oscoin/Deployment/Node.hs
src/Oscoin/Deployment/Node/GCE.hs
src/Oscoin/Deployment/Node/Options.hs
src/Oscoin/Deployment/Options.hs
src/Oscoin/Node/Options.hs
test/Integration/Test/Executable.hs
test/Test/Oscoin/Node/Options/Gen.hs

Every build will execute a validation of the deployment configuration for a oscoin full node. The buid for the `master` branch will deploy that configuration to Google Compute Engine (GCE).
A machine configuration consists of the CLI options passed to the `oscoin` executable, a systemd unit, and a [cloud-init](https://cloud-init.io) configuration which installs the systemd unit, and does other things which are specific to the cloud provider and VM image used. Currently the only supported configuration is to run `oscoin` as a Docker container on GCE using Google's [Container Optimized OS](https://cloud.google.com/container-optimized-os/docs) (COS).
The cloud (GCE) configuration is kept as minimalistic as possible: a managed instance group is created, for which the instance template …

Continuous Deployment (aka "devnet")

---

.hlint.yaml
package.yaml
src/Oscoin/Consensus/Types.hs
src/Oscoin/Prelude.hs
src/Oscoin/Protocol/Sync.hs
src/Oscoin/Protocol/Sync/Mock.hs
src/Oscoin/Protocol/Sync/RealWorld.hs
src/Oscoin/Storage/Block/Pure.hs
test/Test/Oscoin/Protocol.hs
test/Test/Oscoin/Protocol/Sync.hs

This PR ships the first part of #531 , and follows the spec outlined [here](https://hackmd.io/2cPkrWTjTIWo2EmHZpPIQw?both). 
It's unfortunately another almost-1k-big PR, but the commit should be hopefully be reviewable in isolation and I am happy to pair-review this with people. As the PR is already quite substantial but definitely more stuff needs to be implemented, I think it's beneficial if we start with the basics. I wouldn't antagonise too much on the performance side of things as I am aware this is pretty much just a reference implementation and I didn't even try to be efficient here 😬 .

Node syncing - Part 1 (Types, abstractions, sim monad and basic tests)

---

src/Oscoin/CLI.hs
src/Oscoin/CLI/Command.hs
src/Oscoin/CLI/Parser.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
test/Oscoin/Test/CLI/Helpers.hs
test/Oscoin/Test/HTTP/Helpers.hs

To run the node with OscoinTx (#568) we need to create a genesis block for the Oscoin ledger (#589). We prepare for this by removing the inclusion of transactions in the genesis block. While we might want to have that feature later the current implementation will not work with the Oscoin ledger. The reason is that currently transactions are signed with the node key, but we need to sign it with a fixed account owner key.

cli: Prepare genesis creation for OscoinTx

---

src/Oscoin/API/Client.hs
src/Oscoin/API/Client/HTTP.hs
src/Oscoin/API/HTTP.hs
src/Oscoin/API/HTTP/Handlers.hs
src/Oscoin/API/HTTP/Internal.hs
src/Oscoin/CLI/Command.hs
src/Oscoin/Data/Query.hs
src/Oscoin/Data/Tx.hs
src/Oscoin/Node.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/API.hs

As part of implementing the Ledger API for the devnet (#549) we prepare the `Client.getState`. We change the interface of `Client.getState` so that it matches the expected interface defined in #549 while retaining the legacy tx under the hood.
* Eliminate `getPath` as it is unused
* Rename `getPathLatest` to `getStateValue`
* Eliminate the `QueryVal` associated type. State values are (for now) only `ByteString`
* Change the `key` argument type from `[Text]` to `ByteString`. This requires us to encode the keys with base58 when sending it over HTTP.

Prepare Client.getState for OscoinTx

---

README.rst
src/Oscoin/Node/Options.hs

To make it easier to start nodes we document the `--beneficiary` in the Readme and provide better help text.
Closes #570.

Document beneficiary option in readme

---

exe/node/Main.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
src/Oscoin/Storage/Ledger.hs
test/Oscoin/Test/Consensus/Nakamoto.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/Crypto/Blockchain/Eval.hs
test/Test/Oscoin/DummyLedger.hs
test/Test/Oscoin/Storage/Ledger.hs

We change the `Evaluator` type to make it compatible with the evaluation functions of the Oscoin ledger. 
Fixes #591
This commit eliminates the tests for `buildBlock`. The function is now mainly glue code and tests would require substantial ammounts of code.

Change 'Evaluator' type to prepare for OscoinTx

---

scripts/deploy/gce/bootstrap
scripts/deploy/gce/etc/cloud-init/monitoring.yaml
scripts/deploy/gce/etc/grafana/grafana.ini
scripts/deploy/gce/etc/grafana/provisioning/dashboards/oscoin.json
scripts/deploy/gce/etc/grafana/provisioning/dashboards/p2p.json
scripts/deploy/gce/etc/grafana/provisioning/dashboards/rts.json
scripts/deploy/gce/etc/grafana/provisioning/datasources/prometheus.yaml
scripts/deploy/gce/etc/letsencrypt/renewal-hooks/deploy/fix-permissions
scripts/deploy/gce/etc/prometheus/prometheus.yaml
scripts/deploy/gce/etc/systemd/system/certbot-renew.service
scripts/deploy/gce/etc/systemd/system/certbot-renew.timer
scripts/deploy/gce/etc/systemd/system/grafana.service
scripts/deploy/gce/etc/systemd/system/prometheus.service
scripts/deploy/gce/monitoring
scripts/deploy/gce/node
scripts/gce/port-forward
src/Oscoin/Deployment/Internal/GCE.hs
src/Oscoin/Deployment/Internal/Systemd.hs

Makes available a simple monitoring server at https://monitoring.os.computer:3000
The provisioning is rather procedural atm due to various quirks. After running it for another 300x, I might feel confident to collapse more things into the cloud-init config.
**Caveats**
* The prometheus Web UI is not exposed on the internet, as it doesn't support authentication.
Use SSH port-forwarding to access it: `gcloud compute ssh oscoin-monitoring --zone=europe-west3-a --ssh-flag="-L 9090:localhost:9090"`, or the included script `scripts/gce/port-forward`
* Using port 3000 instead of 443 is a bit unfortunate, we'll have to build a custom `grafana` image with the `net_bind_service` capability set on the executable
* Annoyingly, there is still no sane method to manage a set of "default" dashboards, …

Monitoring

---

test/Test/Oscoin/Protocol/Sync.hs

This commit ensures that whenever `spinUpNode` throws and the async is
cancelled, the failure is propagated to the main thread, so that the
test runner doesn't hang. In normal conditions `spinUpNode` should never throw, but as the IO tests try to actually perform HTTP connections, they are by nature a bit flaky, so that's definitely better for the testsuite to fail rather than hang.

Improve robustness of syncing tests

---

scripts/deploy/gce/etc/systemd/system/grafana.service

Note that we need to tear down the iptables rule on ExecStopPost, as it
would interfere with certbot.

Make Grafana reachable on port 443

---

.hlint.yaml
src/Oscoin/P2P.hs

If we run out of active peers after protocol bootstrap, try finding some
via disco (note that the gossip protocol might be able to recover, too).
Closes #442

Always keep on discovering

---

src/Oscoin/Deployment/Node/GCE.hs

Something else seems to be disturbed by the use of `0.0.0.0`, which I'm not quite able to see at this time of the day. Graphs look much more sensible with the sensible choice of binding to the private IP.
We should probably disallow passing `0.0.0.0` altogether.

GCE: Set host to private IPv4

---

.hlint.yaml
src/Oscoin/Deployment/Internal/GCE.hs
src/Oscoin/Deployment/Node/GCE.hs

Fixes #581
Note: this is mainly for operator convenience (you don't have to remember to type `docker logs` instead of `journalctl` when looking at logs on the machine). There [are some ways](https://docs.docker.com/config/containers/logging/journald/) to customise this further, eg. adding the current `network` as a `journald` tag. I'll leave that for a future PR.

GCE: Funnel logs through journald

---

cloudbuild.yaml

We have a quota of 24 CPUs/region, and run almost everything in europe-west1, exceeding the quota on a rolling update.

Set region for CD to europe-west3

---

.hlint.yaml

While the intention is noble (consistency), in practice these rules are often annoying because things may read more natural when given a different name. The rule of qualifiying both `Set` and `HashSet` as `Set` also prevents importing both qualified.
Since naming things is considered part of computer science (and one of the hardest parts about it), I am proposing to leave it up to the author.

hlint: Leave import qualification to the developer

---

exe/node/Main.hs
src/Oscoin/P2P.hs
src/Oscoin/P2P/Disco.hs
src/Oscoin/P2P/Disco/Trace.hs
src/Oscoin/P2P/Handshake/Trace.hs
src/Oscoin/P2P/Trace.hs
src/Oscoin/P2P/Types.hs
src/Oscoin/Telemetry.hs
src/Oscoin/Telemetry/Events.hs
test/Integration/Test/Executable.hs

Also:
* emit `NodeIsolated` event if/when we don't have any peers during continuous disco
* tame the giant NotableEvent pattern match a bit.

Actually disco forever

---

exe/node/Main.hs
package.yaml
src/Oscoin/CLI/KeyStore.hs
src/Oscoin/Crypto/PubKey.hs
src/Oscoin/Crypto/PubKey/FileStore.hs
src/Oscoin/Crypto/PubKey/Internal.hs
src/Oscoin/Crypto/PubKey/Mock.hs
src/Oscoin/Crypto/PubKey/RealWorld.hs
test/Main.hs
test/Test/Oscoin/Crypto/PubKey/FileStore.hs

We extract the functionality to read and write key paris to disk from `Oscoin.CLI.KeyStore` into `Oscoin.Crypto.PubKey.FileStore`. This makes this functionality easier to use since we are providing just functions instead of an MTL-style type class.
This is a necessary step towards having separate key management for the node keys and the account keys (#578).

Reusable keypair file storage

---

cloudbuild.yaml
exe/node/Main.hs
src/Oscoin/Node/Options.hs
src/Oscoin/Telemetry/Logging.hs
src/Oscoin/Telemetry/Options.hs
test/Test/Oscoin/Node/Options/Gen.hs
test/Test/Oscoin/Telemetry/Gen.hs

Deploy using debug logging and no layout + colour.
I left the defaults at colourful logging for convenience, at the expense of CLI options and logger defaults no differing.

Configure logging explicitly, instead of relying on `Environment`

---

src/Oscoin/Deployment/Internal/GCE.hs

Apparently, the fluentd version which comes with COS doesn't understand `match` (yet), and just silently ignores the source.
Note that there is at least one builtin rule which may cause log records to be shipped multiple times: any journal message with severity >= warning will end up `logName=projects/[PROJECT]/logs/cos_journal_warning`.

GCE: fix log source

---

.gitignore
exe/node/Main.hs
src/Oscoin/Protocol/Sync.hs
src/Oscoin/Protocol/Sync/RealWorld.hs

Fix #628. 
This PR extends the `sync` interface for the `RealWorld` implementation with an `onReady` callback of type `Either SyncError (LocalTip c tx s, RemoteTip c tx s) -> m ()` which will be called once the node completed the first (mandatory) sync round.
The use of `Either` in the callback ensure that in case of errors (for example if the node is isolated) the miner will be started anyway, and the error propagated to the callback which then can deal with it (or ignore it).
At the moment in `exe/Main.hs` we are not doing anything with the result of the sync process, but future PR might capitalise on this by using the local & remote tips in interesting ways.

Start the miner only after first sync finishes

---

src/Oscoin/API/Types.hs
src/Oscoin/Crypto/Blockchain/Eval.hs
src/Oscoin/Telemetry.hs
src/Oscoin/Telemetry/Events.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/API.hs
test/Test/Oscoin/Crypto/Blockchain/Eval.hs
test/Test/Oscoin/DummyLedger.hs
test/Test/Oscoin/Storage/Ledger.hs

Errors are encoded in the transaction output. We change the `Evaluator` type accordingly.

Remove errors from block evaluator

---

src/Oscoin/Crypto/Blockchain/Block.hs
test/Integration/Test/Executable.hs
test/Oscoin/Test/Consensus/Nakamoto.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Generators.hs
test/Oscoin/Test/Crypto/Blockchain/Block/Helpers.hs
test/Oscoin/Test/Crypto/Blockchain/Generators.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Oscoin/Test/Storage/Block/SQLite.hs
test/Test/Oscoin/Crypto/Blockchain/Eval.hs
test/Test/Oscoin/Protocol/Sync.hs
test/Test/Oscoin/Storage/Block/Orphanage.hs
test/Test/Oscoin/Storage/Ledger.hs

We introduce `someSealedGenesisBlock` and `someSealedGenesisBlock'` in `Oscoin.Test.Crypto.Blockchain.Block.Generators` which allow us to simplify test code that relies on some fixed genesis block
As a result we can eliminate the block constructors `emptyGenesisBlock` and `emptyGenesisFromState` from `Oscoin.Crypto.Blockchain.Block`.
As part of the change we also merge `defaultBeneficiary` into the `Block.Generators` module and delete `Oscoin.Test.Crypto.Blockchain.Block.Helpers`

Better suited genesis block constructors for tests

---

src/Oscoin/API/Client.hs
src/Oscoin/API/Client/HTTP.hs
src/Oscoin/API/HTTP.hs
src/Oscoin/API/HTTP/Handlers.hs
src/Oscoin/API/Types.hs
src/Oscoin/CLI.hs
src/Oscoin/CLI/Command.hs
test/Oscoin/Test/API/HTTP/TestClient.hs
test/Oscoin/Test/CLI/Helpers.hs
test/Test/Oscoin/API.hs

Before, the `Client` interface was fixed to the legacy transaction type. To make the Ledger API work with OcoinTx (#549) we make it polymorphic in the transaction type.
To make this easier we include the following refactorings in separate commits:
* Remove API client from CLI. It is currently unused. We are also not going to build on `MonadCLI` for the account CLI that will use the client.
* We remove `getTransaction` from the node’s HTTP API. The endpoint in its current is not needed for anything. It also does not match the specification of that endpoint documented in the specs. Instead of carrying this dead weight around we are removing it. This was briefly discussed with and okayed by @cloudhead.

Make 'Client' polymorphic in tx

---

src/Oscoin/Data/Tx.hs
test/Oscoin/Test/HTTP/Helpers.hs
test/Test/Oscoin/Protocol/Sync.hs

To make it easier to change `TxOutput` from `OscoinTx` we decouple it from `TxOutput` from `Tx` (the legacy tx) by changing the `TxOutput` type family instance. This change has some repercussions and requires us adapt `withNode` from `Oscoin.Test.HTTP.Helpers`.
This in turn would require us to run the sync tests with the OscoinTx evaluator. Since this evaluator does not yet exist we opt for running the sync tests with the legacy tx. This requires a switch to the memory block store.

Decouple legacy tx output from oscoin tx output

---

scripts/deploy/gce/node

Instance templates are global resources.

Deployment: Skip creating instance template if already exists.

---

scripts/deploy/gce/node

Regional managed instance groups must use max-surge >= # of zones. Note
that this may temporarily create more than one mining node. Let's see
how it works out.

Deployment: min max-surge

---

scripts/deploy/gce/node

The configuration (miner/validator) is different per-region, hence each
region needs their own template.

Deployment: Per-region instance template
